### ISSUE TITLE
Menentukan Metode Pengembangan Software

### ISSUE THREAD

**Issue by mahesasunts** [gunadarma-academy/asde-screaming-airman#1]
Referensi : http://www.itinfo.am/eng/software-development-methodologies/
unduh : [selectingdevelopmentapproach.pdf](https://github.com/gunadarma-academy/asde-screaming-airman/files/176005/selectingdevelopmentapproach.pdf)

@juniorlie @annekeannassia @HendryGustin buka link tsb, baca, dan diskusikan mana yang paling cocok untuk project ini

Kalau kalian punya referensi lain, taruh di sini aja

**Comment by juniorlie** [comment]
utk kita yg kurang pengalaman, Waterfall cocok, tp kyknya udh ketinggalan jaman, lelet, dan butuh dokumentasi yg banyak. Kalo Prototype (dan di kelas gk ada yg pake), bagus sih, cuma gw bingung nanti yg jadi user siapa. Gw saranin jgn Incremental karena produk kita mirip" dengan kelompok Haidar yg pake Incremental juga (nanti kesannya kita ngikutin). Spiral gw kurang ngerti, dan kyknya ribet, perlu org yg pengalaman buat nentuin iterasi tiap levelnya. RAD (Iterative Prototyping) bagus utk proyek" kecil kyk yg sekarang kita bikin. Jadi menurut gw ada dua pilihan antara Prototype atau RAD.

**Comment by mhaidarhanif** [comment]
@juniorlie Kalau tim Michi pakainya _Lean/Minimal Kanban with GitHub Workflow_ jun. Sifatnya doang yang _incremental_ atau _constant improvement_ pada pengembangannya. (https://github.com/gunadarma-academy/asde-michi/issues/2)

Referensi tentang SDLC populer: https://github.com/gunadarma-academy/ASDE/issues/1

**Comment by juniorlie** [comment]
@mhaidarh terima kasih atas jawabannya bung haidar. Kalau tim Screaming Airman rencananya mau pake Prototype / RAD. Ada masukan?

**Comment by mhaidarhanif** [comment]
@juniorlie Kalau menurut hemat saya, bisa apapun menyesuaikan dengan pemahaman dan preferensi keseluruhan anggota tim, begitulah, saudara Junior.

**Comment by juniorlie** [comment]
@mhaidarh oke terima kasih saudara Haidar. Best of luck. Godspeed.

**Comment by HendryGustin** [comment]
link unduh : http://www.ccpe.csulb.edu/spin/media/pdf/jo_spin-20100212_sw_arch_5w1h_.pdf
@mahesasunts @juniorlie @annekeannassia coba diresapi dulu..

Kalau ada yg lebih bagus boleh dishare lg ya

**Comment by mahesasunts** [comment]
Metode pengembangan menggunakan Prototype
